### ISSUE TITLE
Provide full fixture data

### ISSUE THREAD

**Issue by dashersw** [GallagherAiden/footballSimulationEngine#17]
@GallagherAiden can you provide a fixture data to get the engine started? The requirements for `initiateGame`, with two full teams with correct starting positions and a pitch JSON?

One has to figure out the whole team structure and starting positions only by looking at the README, and as the codebase is growing rapidly, it's hard to keep track.

Currently my code is breaking because I'm missing fitness property from players. It would be great if you could provide an up-to-date fixture json that evolves with the codebase, so the users can take and use them right away.

**Comment by GallagherAiden** [comment]
Started a new directory to give fixture data.
https://github.com/GallagherAiden/footballSimulationEngine/tree/master/init_config
Is this ok @dashersw ?

**Comment by dashersw** [comment]
Thank you @GallagherAiden , it's great. Could you lint the files? Also, need examples on how to make use of these json's.

**Comment by GallagherAiden** [comment]
https://github.com/GallagherAiden/footballSimulationEngine/commit/6edb0cd884d2dc50dddb89884a1af8999cd1b56b
Have linted and added an example implementation.

**Comment by GallagherAiden** [comment]
@dashersw does: https://github.com/GallagherAiden/footballSimulationEngine/blob/master/init_config/index.js
give the sort of example you would expect? I will include the running of this file as part of the new test cases being created to ensure no future regression

**Comment by dashersw** [comment]
Yes, this works!
