### ISSUE TITLE
Players don't move with much intent

### ISSUE THREAD

**Issue by GallagherAiden** [GallagherAiden/footballSimulationEngine#26]
Improve player movement to make the game more interactive.
Either:
   - PreMap a players intended route (like with ballIterations[]) to an intended location and check if any conflict to that path is found each turn.
   - improve the ‘action’ selector to choose to run more often for players with the ball, whilst also setting movement to be more fixed towards an open space upfield (intended position) with players moving more fluidly.

**Comment by LeanKhan** [comment]
Hi, I am also working on a football simulation built with NodeJS. I like the structure of your own game. Mine is more messy. What I did about players moving with intent was I made all the other players in the attacking team (except the GK) to move towards the ball.

**Comment by LeanKhan** [comment]
> 
> 
> Hi, I am also working on a football simulation built with NodeJS. I like the structure of your own game. Mine is more messy. What I did about players moving with intent was I made all the other players in the attacking team (except the GK) to move towards the ball.

Like in normal soccer. That way the attacking team is pressing towards the ball. What do you think?

**Comment by GallagherAiden** [comment]
I added an intentPOS which showed where the player was moving to in v3 and have updated it a little in v4 because there were a few bugs in there where it wasn't being set. I did try all players moving towards the ball but eventually they all end up circling the ball. The intentPOS and formation checker basically move towards the ball but also try to keep the teams formation
