### ISSUE TITLE
great program

### ISSUE THREAD

**Issue by flylee2004** [GallagherAiden/footballSimulationEngine#30]
1 How many games did you simulate, and did the results match the normal distribution?
2 How many moves do you think are more cooperative in a game? Can 5000 be?
3 What should I do if I want to change the point on the court to the player's name or image?
Thank you

**Comment by flylee2004** [comment]
HI ，my English is poor,sorry ,but thank you for your share again

**Comment by flylee2004** [comment]
penalty_taking and jumping what is that mean??

**Comment by flylee2004** [comment]
sometimes the ball and player stop,why?Most of the iterations in 3 4000 occur

**Comment by GallagherAiden** [comment]
1. There are currently no result metrics - I've created an issue: https://github.com/GallagherAiden/footballSimulationEngine/issues/31
2. I would do between 4000 and 6000 iterations for each half.
3. I don't provide graphics as part of the node module, but in https://github.com/GallagherAiden/footballsimulationexample you could adapt:
```
 for (i = 2; i < result.length - 1; i++) {
				ctx.beginPath();
				ctx.moveTo(result[i], result[i + 1]);
				ctx.lineTo(result[i] + 1, result[i + 1] + 1);
				if (i < 24) {
					ctx.strokeStyle = '#ff0000';
				} else if (i > 12 && i < result.length - 3) {
					ctx.strokeStyle = '#0000FF';
				} else {
					ctx.strokeStyle = '#000000';
				}
				ctx.stroke();
				i++;
			}
```
in https://github.com/GallagherAiden/footballsimulationexample/blob/master/public/js/match.js to write the player names instead.
4. penalty_taking is how good they are at taking a penalty and 'jumping' is how high they can jump including their height.

**Comment by flylee2004** [comment]
It’s a great honor to have the opportunity to communicate with a god like you. I set the team2 player attribute to 99. I simulated it hundreds of times. There are often players and balls that don’t move, but the iteration continues. Only restart the matchmatch to solve the problem. Do you have a solution to this problem? And I found that rating and fitness are not very useful in the game.




------------------ 原始邮件 ------------------
发件人: "Aiden Gallagher"<notifications@github.com>;
发送时间: 2019年1月2日(星期三) 凌晨3:48
收件人: "GallagherAiden/footballSimulationEngine"<footballSimulationEngine@noreply.github.com>;
抄送: "蚊帐里的故事"<149006383@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [GallagherAiden/footballSimulationEngine] great program (#30)



 
There are currently no result metrics - I've created an issue: #31
 
I would do between 4000 and 6000 iterations for each half.
 
I don't provide graphics as part of the node module, but in https://github.com/GallagherAiden/footballsimulationexample you could adapt:
   for (i = 2; i < result.length - 1; i++) { 				ctx.beginPath(); 				ctx.moveTo(result[i], result[i + 1]); 				ctx.lineTo(result[i] + 1, result[i + 1] + 1); 				if (i < 24) { 					ctx.strokeStyle = '#ff0000'; 				} else if (i > 12 && i < result.length - 3) { 					ctx.strokeStyle = '#0000FF'; 				} else { 					ctx.strokeStyle = '#000000'; 				} 				ctx.stroke(); 				i++; 			}  
in https://github.com/GallagherAiden/footballsimulationexample/blob/master/public/js/match.js to write the player names instead.
 4. penalty_taking is how good they are at taking a penalty and 'jumping' is how high they can jump including their height.

**Comment by GallagherAiden** [comment]
Hi @flylee2004 - I'll look to fix the players and ball getting stuck and will associate it with this issue: https://github.com/GallagherAiden/footballSimulationEngine/issues/33 

I'm looking to work in ratings and fitness into the algorithms of success for tackles, free kicks, penalties, shooting etc in the next version I publish.

**Comment by GallagherAiden** [comment]
@flylee2004 please let me know if you want anything specific raising or fixing

**Comment by GallagherAiden** [comment]
Hi @flylee2004 I have added a temporary fix for players getting stuck: https://github.com/GallagherAiden/footballSimulationEngine/commit/7bf5cf846b752f52049abe1fffa6f23047179121 
this is not on the npm node module but in this repository (so you will need to clone the repo). it may or may not be included in the next version. Please let me know if there's anything else you would like help with
