### ISSUE TITLE
Add test for simulating multiple games for result data

### ISSUE THREAD

**Issue by GallagherAiden** [GallagherAiden/footballSimulationEngine#31]

**Comment by flylee2004** [comment]
team1:team2
3:0  4:0  3:0   4:1   3:0   1:0   6:0   1:1   2:0    1:1    8:2   2:0   2:0    1:1    2:2    4:0    1:0   0:2    0:0   1:0   2:1

I did some simulations, the score is as follows, but the strength of my team2 is very strong, why is it always lost? ? ? The values of the two teams are as follows:

**Comment by flylee2004** [comment]
team1

{
  "name": "Team1",
  "players": [{
      "name": "曾诚",
      "position": "GK",
      "rating": "75",
      "skill": {
        "passing": "78",
        "shooting": "12",
        "tackling": "75",
        "saving": "75",
        "agility": "70",
        "strength": "60",
        "penalty_taking": "45",
        "jumping": "235"
      },
      "startPOS": [ 60 , 0],
"injured": false
    },
    {
      "name": "李学鹏",
      "position": "LB",
      "rating": "90",
      "skill": {
        "passing": "83",
        "shooting": "40",
        "tackling": "32",
        "saving": "10",
        "agility": "30",
        "strength": "30",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 30, 20 ],
"injured": false
    },
    {
      "name": "范志毅",
      "position": "CB",
      "rating": "84",
      "skill": {
        "passing": "78",
        "shooting": "37",
        "tackling": "21",
        "saving": "10",
        "agility": "76",
        "strength": "59",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 50, 20 ],
"injured": false
    },
    {
      "name": "冯潇霆",
      "position": "CB",
      "rating": "75",
      "skill": {
        "passing": "33",
        "shooting": "76",
        "tackling": "76",
        "saving": "10",
        "agility": "83",
        "strength": "73",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 70, 20 ],
"injured": false
    },
    {
      "name": "吴承瑛",
      "position": "RB",
      "rating": "82",
      "skill": {
        "passing": "66",
        "shooting": "65",
        "tackling": "81",
        "saving": "10",
        "agility": "70",
        "strength": "90",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 90, 20 ],
"injured": false
    },
    {
      "name": "于汉超",
      "position": "LM",
      "rating": "87",
      "skill": {
        "passing": "51",
        "shooting": "88",
        "tackling": "81",
        "saving": "10",
        "agility": "65",
        "strength": "85",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 30, 120 ],
"injured": false
    },
    {
      "name": "韦世豪",
      "position": "CM",
      "rating": "41",
      "skill": {
        "passing": "33",
        "shooting": "66",
        "tackling": "55",
        "saving": "10",
        "agility": "70",
        "strength": "40",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 50, 120 ],
"injured": false
    },
    {
      "name": "蒿俊闵",
      "position": "CM",
      "rating": "99",
      "skill": {
        "passing": "88",
        "shooting": "95",
        "tackling": "91",
        "saving": "10",
        "agility": "90",
        "strength": "75",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 70, 120 ],
"injured": false
    },
    {
      "name": "万志刚",
      "position": "RM",
      "rating": "79",
      "skill": {
        "passing": "56",
        "shooting": "79",
        "tackling": "74",
        "saving": "10",
        "agility": "40",
        "strength": "40",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 90, 120 ],
"injured": false
    },
    {
      "name": "郜林",
      "position": "ST",
      "rating": "75",
      "skill": {
        "passing": "83",
        "shooting": "88",
        "tackling": "59",
        "saving": "10",
        "agility": "43",
        "strength": "76",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 50, 270 ],
"injured": false
    },
    {
      "name": "杨旭",
      "position": "ST",
      "rating": "88",
      "skill": {
        "passing": "73",
        "shooting": "61",
        "tackling": "44",
        "saving": "10",
        "agility": "43",
        "strength": "88",
        "penalty_taking": "77",
        "jumping": "235"
      },
      "startPOS": [ 70, 270 ],
"injured": false
    }
  ],
  "manager": "Alex Ferguson"
}

**Comment by flylee2004** [comment]
team2

{
  "name": "ThatTeam",
  "rating": 88,
  "players": [
    {
      "name": "Ian Smith",
      "position": "GK",
      "rating": "75",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "290"
      },
      "startPOS": [
        340,
        0
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Fred Smith",
      "position": "LB",
      "rating": "90",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        80,
        80
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Emma Smith",
      "position": "CB",
      "rating": "84",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        230,
        80
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Jim Smith",
      "position": "CB",
      "rating": "75",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        420,
        80
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Emily Smith",
      "position": "RB",
      "rating": "82",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        600,
        80
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Gregory Smith",
      "position": "LM",
      "rating": "999",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        80,
        270
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Arthur Smith",
      "position": "CM",
      "rating": "99",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        230,
        270
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Diane Smith",
      "position": "CM",
      "rating": "99",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "90",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        420,
        270
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Colin Smith",
      "position": "RM",
      "rating": "79",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        600,
        270
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Wayne Smith",
      "position": "ST",
      "rating": "75",
      "skill": {
        "passing": "83",
        "shooting": "88",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        280,
        500
      ],
      "fitness": 100,
      "injured": false
    },
    {
      "name": "Aiden Smith",
      "position": "ST",
      "rating": "88",
      "skill": {
        "passing": "99",
        "shooting": "99",
        "tackling": "99",
        "saving": "99",
        "agility": "99",
        "strength": "99",
        "penalty_taking": "99",
        "jumping": "235"
      },
      "startPOS": [
        440,
        500
      ],
      "fitness": 100,
      "injured": false
    }
  ]
}

**Comment by flylee2004** [comment]
Have I a problem with the score setting here, which caused the result of the game to be inverted.

**Comment by GallagherAiden** [comment]
Added an output for the latest updates in preparation for v2.2.0
https://github.com/GallagherAiden/footballSimulationEngine/commit/a273b215af6680456405fe02a70be43f2745381a
