### ISSUE TITLE
In the most of the matches fouls are near to 0

### ISSUE THREAD

**Issue by marcozdev** [GallagherAiden/footballSimulationEngine#4]
Hello i'm trying this algorithm but i noticed that fouls are most of the times near to 0.. 
What i'm doing wrong in configuration?

var pitch = {
		"pitchWidth": 120,
	 	"pitchHeight": 600
	};

var pos_coords = [
	[60,0],
	[20,60],
	[100,60],
	[50,50],
	[70,50],
	[20,200],
	[100,200],
	[60,150],
	[60,250],
	[50,290],
	[70,300],
];

var pos = [
	"GK",
	"TS",
	"TD",
	"DC",
	"DC",
	"ES",
	"ED",
	"CC",
	"COC",
	"ATT",
	"ATT"
];

Players are generated for testing purpose with this function
var generatePlayers = function(name, overall) {
	overall = parseInt(overall);
	var players = new Array();
	for (var i = 1;i<= 11; i++) {
		players.push({
      "name": "Player_" + name + "_" + i,
      "position": pos[i-1],
      "rating": overall,
      "skill": {
        "passing": overall,
        "shooting": overall,
        "tackling": overall,
        "saving": overall,
        "agility": overall,
        "strength": overall,
        "penalty_taking": overall,
        "jumping": (120+overall)
      },
      "startPOS": pos_coords[i-1],
      "injured": false
    });
	}
	return players;
}

Usually i test it with overall between 60 and 100

But results are like this:
Home
{"goals":2,"shots":6,"corners":8,"freekicks":0,"penalties":0,"fouls":0}
Away:
{"goals":1,"shots":6,"corners":3,"freekicks":0,"penalties":0,"fouls":0}

I'm running without any graphical interface, simulating the whole match through promise loops (waiting resolve of every promise) and starting automatically the second-half

For: 45/60 iterations per half

Thank you

**Comment by GallagherAiden** [comment]
made some alterations to the code to make players more likely to tackle. I'll add it to the next version of the code (2.0.2)

**Comment by GallagherAiden** [comment]
updated in 2.0.2
