### ISSUE TITLE
Player variable undefined 

### ISSUE THREAD

**Issue by M3sca** [GallagherAiden/footballSimulationEngine#62]
Sometimes I have see that in the resolveTacke and resolveSlide functions of file lib\actions.js the variable "thatPlayer" is undefined and so after few row the engine goes in error.
I had a fix on them. I have put a check if a player is undefined, exit from the function.

**Comment by GallagherAiden** [comment]
@M3sca I believe this error should be handled better now. https://github.com/GallagherAiden/footballSimulationEngine/pull/63

Let me know if not resolved and I will reopen and look again
