### ISSUE TITLE
highNumb somethings is float

### ISSUE THREAD

**Issue by M3sca** [GallagherAiden/footballSimulationEngine#64]
I have seen that in the function getInterceptTrajectory of file playerMovement.js the variable highNumb is always a integer but somethings it became float and this cause a crash in the row with "new Array()"

**Comment by M3sca** [comment]
I have add a conversion "new Array(Math.round(highNum))"  to fix it!

**Comment by GallagherAiden** [comment]
Perfect, do you want to do a pull request?

**Comment by M3sca** [comment]
Ok, thanks!

**Comment by M3sca** [comment]
I need to create a fork or you create a pull request?
@GallagherAiden

**Comment by GallagherAiden** [comment]
fixed in here https://github.com/GallagherAiden/footballSimulationEngine/commit/04fc2e306c45642453b237853e9dd5fdf7764b2b
