### ISSUE TITLE
Occasionally only one player runs towards the ball

### ISSUE THREAD

**Issue by GallagherAiden** [GallagherAiden/footballSimulationEngine#66]

**Comment by kiknaio** [comment]
Is there any update here?

**Comment by GallagherAiden** [comment]
Latest iteration deals much better with this. I have expanded the radius that players react to the ball and it is showing a much better game flow in my simulations. Not perfect, but much better. Will have to rethink how the players move about the pitch and react in the next iteration. Closing for now though.
