### ISSUE TITLE
AutoGoal

### ISSUE THREAD

**Issue by M3sca** [GallagherAiden/footballSimulationEngine#67]
I simulated serveral matches with two teams.
I found a problem.
For example a match ended 2-0.
If I search in the players stats I found only 1 goal.
I have found that in the function where is set the scorer, the player who made the last touch is in the opposite team.
This is an autogoal?

**Comment by GallagherAiden** [comment]
I think I have fixed this in the latest updates. There were a number of places where it wasn't getting assigned properly. I've added a new item in the iteration.json as below. This keeps track of the last person to touch the ball which fixes issues both with goal scoring and setting corners/goal kicks which was buggy before. Please reopen if you see any further issues

"lastTouch": {
         "playerName": "Peter Johnson",
         "playerID": 78883930303030109,
         "teamID": 72464187147564590
      },
