### ISSUE TITLE
Find Index with player name

### ISSUE THREAD

**Issue by M3sca** [GallagherAiden/footballSimulationEngine#68]
When I have debugged source code I have found that the script search a player use a compare with the name.
I think this can be a problem because two player can have the same name.

**Comment by GallagherAiden** [comment]
I think I have caught all of these instances in the latest updates. If you find another reopen this case and I will fix. Thanks for raising this issue

https://github.com/GallagherAiden/footballSimulationEngine/commit/d2afd174693572f2be30906612c8afc53717ff3d#diff-ccec8a6cd159796cbca5166b919d75afa7e362394ac31ed3ef472ac5af0608da
