### ISSUE TITLE
Text-based, interactive football game based on footballSimulationEngine

### ISSUE THREAD

**Issue by dashersw** [GallagherAiden/footballSimulationEngine#7]
30 years ago there were paid phone line games where a commentator would present the match, and you could press numbers on your phone to either pass, shoot, dribble or tackle the ball depending on the situation. Then the engine would tell you the outcome of your action, and you were trying to win the match.

20 years ago I was playing with an mIRC bot that employed the same logic between two human players — the bot would present the match's important positions, and players would either pass, shoot, dribble or tackle the ball by typing into the channel. The bot then would decide the outcome. We had a lot of fun doing entire leagues, even nominating top scorers and top assists.

Growing up with these, for some time I'm in the search for such an engine that I can turn into a similar game for modern chat applications like Slack, Telegram, Facebook Messenger and even iMessage. footballSimulationEngine looks like a great start. Would you be up for collaboration on such a game? If not, can I fork your engine and use it?

**Comment by GallagherAiden** [comment]
Nothing to do, so closing. Happy to make any changes to help, feel free to make specific issues :)
