### ISSUE TITLE
Players return to pitch after red card

### ISSUE THREAD

**Issue by leonardogmachado** [GallagherAiden/footballSimulationEngine#70]
After few simulations I detected that players are returning after red cards.

I did some changes to solve this:

in file "playerMovement.js", I replaced `thisPlayer.currentPOS = ['NP', 'NP']` (in lines: 76, 80, 94 and 98) to:

```
Object.defineProperty(thisPlayer, "currentPOS", {
      value: ['NP', 'NP'],
      writable : false,
      enumerable : true,
      configurable : false
})
```

This way, the property "currentPOS", can't be changeed anymore.

**Comment by GallagherAiden** [comment]
Made this update as you suggested @leonardogmachado but also had to pass certain checks elsewhere in the movement to skip trying to assign a currentPOS value, this removed the errors I was getting in testing. Please reopen if there are any further issues.

https://github.com/GallagherAiden/footballSimulationEngine/commit/d2afd174693572f2be30906612c8afc53717ff3d#diff-540ce1e76c18e5ffec088391993d9b90c4a1f206f7b5cdc171bf94c5b2856feb
